apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- bases/metallb.io_ipaddresspools.yaml
- bases/metallb.io_bgppeers.yaml
- bases/metallb.io_bfdprofiles.yaml
- bases/metallb.io_bgpadvertisements.yaml
- bases/metallb.io_l2advertisements.yaml
- bases/metallb.io_communities.yaml
- bases/metallb.io_servicel2statuses.yaml

patches:
- path: patches/crd-conversion-patch-bgppeers.yaml
  target:
    kind: CustomResourceDefinition
    name: bgppeers.metallb.io
# appends start and stop conversion markers for sed command to post-process
# post-processing changes that into helm templates
- patch: |-
    - op: add
      path: "/spec/conversion/a-metallb-internal-start"
      value: metallb-conversion-start
  target:
    kind: CustomResourceDefinition
    name: bgppeers.metallb.io
- patch: |-
    - op: add
      path: "/spec/conversion/z-metallb-internal-stop"
      value: metallb-conversion-stop
  target:
    kind: CustomResourceDefinition
    name: bgppeers.metallb.io
